version: 2

models:
    - name: testing_ddm_on_model
      tests:
      - dbt_utils.expression_is_true:
          expression: "email = expected_email and phone_number = expected_phone_number"
      columns:
        - name: user_id

        - name: email
          meta:
            sensitive: true

        - name: phone_number 
          meta:
            sensitive: true


