# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: dbt_fivetran
      - id: end-of-file-fixer
        exclude: dbt_fivetran
      - id: check-yaml
        exclude: dbt_fivetran
      - id: check-added-large-files

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        exclude: dbt_fivetran

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [ pydantic, types-PyYAML, types-requests, types-python-dateutil ]
        exclude: dbt_fivetran

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.12
    hooks:
      - id: ruff
        exclude: dbt_fivetran
