name: 'dbt_fivetran_integration_tests'
version: '1.3.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["../macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models: 
  +bind: false # Materialize all views as late-binding
  dbt_fivetran_integration_tests:
    schema: dbt_fivetran_integration_tests 

seeds:

  +quote_columns: false
  dbt_fivetran_integration_tests:
    schema: dbt_fivetran_integration_tests
    ddm:
      data_mask_model:
        +column_types:
          user_id: integer
          email: character varying(500)
          phone_number: character varying(500)

      data_mask_model_expected:
        +column_types:
          user_id: integer
          email: character varying(500)
          phone_number: character varying(500)


on-run-end:
  # - '{{ mask_all_sources() }}'
