default:
  target: default
  outputs:
    default:
      type: redshift
      host: "{{ env_var('DBT_REDSHIFT_HOST') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: 5439
      dbname: dev
      schema: "{{ env_var('DBT_DEV_SCHEMA') }}"
      threads: 4
    prod:
      type: redshift
      host: "{{ env_var('DBT_REDSHIFT_HOST') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: 5439
      dbname: dev
      schema: "{{ env_var('DBT_DEV_SCHEMA') }}"
      threads: 4
