

-- Best practice for this model is to be materialized as view. That is why we have set that here.


/*
    The below sets the old_formula_fields variable to the results of the get_column_values results which queries the field column from the fivetran_formula table.
    The logic here is that the variable will be a list of all current salesforce formula field names. This list is then used within the dbt_utils.star operation to exclude them.
    This allows users with the Fivetran legacy Salesforce fields to ignore them and be replaced by the new fields.
*/




SELECT 
mt.specialisation_c,
mt.number_of_entities_c,
mt.lost_reason_c,
mt.allocation_notes_c,
mt.competitor_selection_required_c,
mt.discount_dollars_approved_c,
mt.next_step,
mt.lid_main_competitors_c,
mt.exclude_from_payment_report_c,
mt.lead_original_lost_reason_c,
mt.referee_s_name_c,
mt.marketing_plan_actioned_c,
mt.lid_order_number_c,
mt.international_opportunity_c,
mt.last_referenced_date,
mt.admin_opportunity_c,
mt.lost_to_a_competitor_c,
mt.discount_before_submitting_to_approval_c,
mt.quote_srr_c,
mt.x_3_rd_party_integrations_c,
mt.record_type_id,
mt.considering_competitors_c,
mt.completed_quote_c,
mt.call_back_date_change_count_c,
mt.lead_original_lost_date_c,
mt.quote_arr_c,
mt.contract_term_c,
mt.discovery_completed_c,
mt.discount_approval_rejected_c,
mt.original_lead_source_sub_type_c,
mt.lead_lost_count_c,
mt.buyc_code_c,
mt.lead_source_sub_type_c,
mt.opportunity_is_closed_c,
mt.opp_lost_to_competitor_c,
mt.regions_serviced_c,
mt.time_on_hold_c,
mt.last_amount_changed_history_id,
mt.terminated_contract_c,
mt.fiscal_quarter,
mt.opportunity_originator_market_c,
mt.became_sql_date_c,
mt.lean_data_days_in_stage_c,
mt.payment_terms_c,
mt.drill_down_source_c,
mt.reactivated_c,
mt.account_id,
mt.sent_notification_days_on_hold_date_c,
mt.lead_original_lost_sub_reason_c,
mt.lean_data_status_info_c,
mt.drift_requested_contact_c,
mt.close_date,
mt.last_modified_date,
mt.lid_delivery_installation_status_c,
mt.legacy_org_id_c,
mt.opportunity_originator_c,
mt.budget_confirmed_c,
mt.reactivated_source_drilldown_c,
mt.lead_score_over_40_no_request_con_c,
mt.date_when_the_stage_is_changed_c,
mt.most_recent_sales_contact_c,
mt.roi_analysis_completed_c,
mt.on_hold_reason_c,
mt.days_in_current_stage_for_report_c,
mt.opp_on_hold_start_date_c,
mt.existing_customer_revenue_type_c,
mt.created_from_lead_c,
mt.zi_campaign_c,
mt.campaign_id,
mt.is_closed,
mt.number_of_locations_c,
mt.requested_contact_c,
mt.bizible_2_bizible_opportunity_amount_c,
mt.purchasing_drivers_c,
mt.synced_quote_id,
mt.referee_s_business_name_c,
mt.became_a_customer_date_c,
mt.opportunity_originator_manager_c,
mt.name,
mt.reactivated_lead_source_sub_type_c,
mt.lid_linked_in_company_id_c,
mt.lid_is_influenced_c,
mt.became_opportunity_date_c,
mt.internal_eh_referer_c,
mt.company_website_c,
mt.delayed_implementation_date_c,
mt.lean_data_routing_action_c,
mt.originally_free_email_c,
mt.description,
mt.opp_loss_reason_detail_c,
mt.lead_original_lost_to_competitor_c,
mt.onboarding_specialist_c,
mt.lead_original_loss_reason_c,
mt.last_close_date_changed_history_id,
mt.pandadoc_tracking_number_c,
mt.expected_revenue,
mt.hero_network_referred_c,
mt.demo_rebook_c,
mt.became_hot_lead_date_c,
mt.opp_on_hold_detail_c,
mt.opp_loss_sub_reason_c,
mt.free_account_c,
mt.payment_frequency_c,
mt.managers_email_c,
mt.stated_payroll_system_other_c,
mt.offer_c,
mt.original_lead_source_type_c,
mt.discount_approval_product_id_c,
mt.lead_original_loss_sub_reason_c,
mt.gclid_c,
mt.zqu_current_generators_c,
mt.lean_data_reporting_total_marketing_touches_c,
mt.stated_hr_system_other_c,
mt.implementation_training_completed_c,
mt.owner_id,
mt.original_point_of_conversion_c,
mt.zqu_tracking_number_c,
mt.lead_source,
mt.products_interested_in_c,
mt.provisioning_notes_c,
mt.type,
mt.referee_s_email_address_c,
mt.most_recent_point_of_conversion_c,
mt.fiscal_year,
mt.lost_sub_reason_c,
mt.id,
mt.demo_sat_date_c,
mt.lead_source_type_c,
mt.employment_split_c,
mt.hr_system_c,
mt.probability,
mt.contract_generated_c,
mt.reactivated_lead_source_type_c,
mt.customer_marketing_executive_manager_c,
mt.original_loss_reason_detail_c,
mt.demo_is_booked_c,
mt.hot_content_download_c,
mt.test_opportunity_c,
mt.vip_strategic_client_c,
mt.no_of_employees_originally_contracted_c,
mt.commercial_model_finalised_c,
mt.next_steps_timelines_c,
mt.forecast_category,
mt.opp_product_discount_requested_user_name_c,
mt.demo_rating_c,
mt.zqu_zuora_config_c,
mt.lid_my_geolocation_latitude_s,
mt.number_of_clients_c,
mt.last_viewed_date,
mt.loss_reason_c,
mt.hero_network_referral_partner_c,
mt.top_pain_points_c,
mt.has_open_activity,
mt.lean_data_reporting_opportunity_source_c,
mt.opp_products_that_needs_discount_c,
mt.lid_my_geolocation_longitude_s,
mt.linked_in_company_id_c,
mt.zqu_delivery_installation_status_c,
mt.content_downloaded_c,
mt.lid_tracking_number_c,
mt.became_workable_lead_date_c,
mt.opp_loss_reason_c,
mt.payroll_handover_notes_c,
mt.no_guided_payroll_zuora_c,
mt.hot_lead_c,
mt.referred_by_a_friend_c,
mt.push_count,
mt.activity_metric_id,
mt.payroll_admin_capability_c,
mt.hubspot_score_40_c,
mt.contact_c,
mt.how_did_you_hear_about_employment_hero_c,
mt.lid_my_date_time_c,
mt.date_demo_booked_c,
mt.x_3_rd_party_integrations_other_c,
mt.opportunity_employees_c,
mt.most_recently_engaged_contact_c,
mt.account_referral_partner_c,
mt.pricebook_2_id,
mt.demo_rating_feedback_c,
mt.implementation_training_kickoff_c,
mt.originally_stated_no_of_employees_c,
mt.reactivated_lead_date_c,
mt.last_modified_by_id,
mt.system_modstamp,
mt.get_started_submission_c,
mt.stage_name,
mt.last_stage_change_date,
mt.stage_at_loss_point_c,
mt.number_of_contacts_roles_assigned_c,
mt.zqu_order_number_c,
mt.trigger_quote_rollup_c,
mt.workable_lead_c,
mt.push_count_c,
mt.originating_lead_id_c,
mt.last_activity_date,
mt.opportunity_closed_date_c,
mt.lid_current_generators_c,
mt.is_won,
mt.payment_method_c,
mt.most_recent_sent_email_c,
mt.fiscal,
mt.partner_for_implementation_c,
mt.opp_on_hold_end_date_c,
mt.created_by_id,
mt.recycled_lead_c,
mt.is_private,
mt.zqu_main_competitors_c,
mt.industry_c,
mt.has_overdue_task,
mt.recycled_lead_date_c,
mt.contact_id,
mt.activity_metric_rollup_id,
mt.stated_payroll_system_c,
mt.is_deleted,
mt.currency_iso_code,
mt.handover_notes_c,
mt.managed_implementations_c,
mt.competitors_considered_c,
mt.sent_notification_days_on_hold_c,
mt.amount,
mt.opp_call_back_date_c,
mt.project_manager_c,
mt.free_account_feature_selection_c,
mt.csat_sent_date_c,
mt.opportunity_originator_profile_c,
mt.secondary_opportunity_owner_c,
mt.marketing_plan_agreed_c,
mt.gong_main_competitors_c,
mt.has_opportunity_line_item,
mt.no_of_guided_hr_implementations_c,
mt.forecast_category_name,
mt.company_linked_in_c,
mt.created_date,
mt.became_mql_date_c,
mt._fivetran_synced,
mt._fivetran_deleted,
null AS total_quantity_c,
CASE WHEN mt.is_won THEN COALESCE(rs1.rsf5,0) ELSE 0 END AS closed_won_arr_c,
jt4.team_c AS owner_team_c,
COALESCE(rs1.rsf4,0) AS no_managed_payroll_products_c,
CONVERT(VARCHAR, jt1.industry_secondary_c) AS account_industry_secondary_c,
CASE WHEN ((COALESCE(EXTRACT(YEAR FROM DATE(mt.created_date)),0)=COALESCE(EXTRACT(YEAR FROM mt.close_date),0)) AND (COALESCE(EXTRACT(MONTH FROM DATE(mt.created_date)),0)=COALESCE(EXTRACT(MONTH FROM mt.close_date),0)) AND mt.is_closed) THEN CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Hero_Referrer','')) THEN 0 ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Organic','')) THEN mt.amount ELSE CASE WHEN (COALESCE(COALESCE(rs1.rsf6,0),0)>COALESCE(0,0)) THEN COALESCE(rs1.rsf7,0) ELSE CASE WHEN (COALESCE(mt.quote_arr_c,0)>COALESCE(0,0)) THEN mt.quote_arr_c ELSE CASE WHEN (COALESCE(UPPER(mt.stage_name),'')=COALESCE(UPPER('Won'),'')) THEN COALESCE(rs1.rsf7,0) ELSE CASE WHEN (COALESCE(UPPER(CONVERT(VARCHAR, jt1.geo_code_c)),'')=COALESCE(UPPER('AU'),'')) THEN (CASE WHEN ((COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_greater_100','')) OR (COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_Less_100',''))) THEN (COALESCE((COALESCE(12,0)*COALESCE(13.36,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Upsell','')) THEN (COALESCE((COALESCE(12,0)*COALESCE(3.56,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE 0 END END) ELSE CASE WHEN (COALESCE(UPPER(CONVERT(VARCHAR, jt1.geo_code_c)),'')=COALESCE(UPPER('NZ'),'')) THEN (CASE WHEN ((COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_greater_100','')) OR (COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_Less_100',''))) THEN (COALESCE((COALESCE(12,0)*COALESCE(10.64,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Upsell','')) THEN (COALESCE((COALESCE(12,0)*COALESCE(2.65,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE 0 END END) ELSE CASE WHEN (COALESCE(UPPER(CONVERT(VARCHAR, jt1.geo_code_c)),'')=COALESCE(UPPER('SG'),'')) THEN (CASE WHEN ((COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_greater_100','')) OR (COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_Less_100',''))) THEN (COALESCE((COALESCE(12,0)*COALESCE(5.00,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Upsell','')) THEN (COALESCE((COALESCE(12,0)*COALESCE(1.25,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE 0 END END) ELSE CASE WHEN (COALESCE(UPPER(CONVERT(VARCHAR, jt1.geo_code_c)),'')=COALESCE(UPPER('MY'),'')) THEN (CASE WHEN ((COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_greater_100','')) OR (COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_Less_100',''))) THEN (COALESCE((COALESCE(12,0)*COALESCE(9.99,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Upsell','')) THEN (COALESCE((COALESCE(12,0)*COALESCE(2.51,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE 0 END END) ELSE CASE WHEN (COALESCE(UPPER(CONVERT(VARCHAR, jt1.geo_code_c)),'')=COALESCE(UPPER('UK'),'')) THEN (CASE WHEN ((COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_greater_100','')) OR (COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_Less_100',''))) THEN (COALESCE((COALESCE(12,0)*COALESCE(6.65,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Upsell','')) THEN (COALESCE((COALESCE(12,0)*COALESCE(1.66,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE 0 END END) ELSE 0 END END END END END END END END END END ELSE 0 END AS created_closed_c,
COALESCE(rs1.rsf18,0) AS no_of_eap_product_c,
jt8.name AS creator_profile_c,
jt6.org_id_c AS org_id_c,
(DATEDIFF(SECOND, mt.date_when_the_stage_is_changed_c, CURRENT_DATE)/(24.0*60*60)) AS days_in_current_stage_c,
1 AS opportunity_c,
COALESCE(rs1.rsf7,0) AS product_arr_c,
COALESCE(rs1.rsf11,0) AS product_recurring_srr_c,
null AS discount_approval_product_link_c,
CASE WHEN mt.is_won THEN COALESCE(rs1.rsf8,0) ELSE 0 END AS won_product_rev_roll_up_recurring_c,
COALESCE(rs1.rsf2,0) AS no_s_013_product_c,
jt5.name AS owner_profile_c,
null AS commission_fee_c,
COALESCE(rs1.rsf13,0) AS product_revenue_roll_up_c,
COALESCE(rs1.rsf24,0) AS no_line_items_to_review_c,
null AS estimated_total_employees_c,
(COALESCE((COALESCE(CONVERT(VARCHAR, EXTRACT(YEAR FROM DATE(mt.created_date))),'')||COALESCE('-','')),'')||COALESCE(CASE EXTRACT(MONTH FROM DATE(mt.created_date)) WHEN 1 THEN '01' WHEN 2 THEN '02' WHEN 3 THEN '03' WHEN 4 THEN '04' WHEN 5 THEN '05' WHEN 6 THEN '06' WHEN 7 THEN '07' WHEN 8 THEN '08' WHEN 9 THEN '09' WHEN 10 THEN '10' WHEN 11 THEN '11' WHEN 12 THEN '12' ELSE 'None' END,'')) AS created_month_c,
1 AS gong_gong_count_c,
mt.id AS record_id_18_d_c,
COALESCE(rs1.rsf1,0) AS no_guided_payroll_products_c,
CASE WHEN CASE WHEN mt.offer_c IS NOT NULL THEN UPPER(mt.offer_c) LIKE '%'||UPPER('May 2020 SME Booster Offer')||'%' ELSE FALSE END THEN 'May 2020 SME Booster Offer' ELSE CASE WHEN (LENGTH(COALESCE(mt.offer_c,''))=0) THEN 'No Offer' ELSE 'Others' END END AS offer_bucket_c,
COALESCE(rs1.rsf9,0) AS monthly_price_roll_up_c,
jt1.name AS opp_account_name_c,
jt11.name AS price_book_c,
null AS valid_billing_account_c,
COALESCE(rs1.rsf17,0) AS qty_opportunity_products_c,
(NOT (mt.demo_sat_date_c IS NULL)) AS demo_sat_c,
jt8.name AS created_by_profile_c,
null AS mkto_si_marketo_analyzer_c,
CASE WHEN (mt.opp_on_hold_end_date_c IS NULL) THEN (DATEDIFF(SECOND, mt.opp_on_hold_start_date_c, CURRENT_DATE)/(24.0*60*60)) ELSE (DATEDIFF(SECOND, mt.opp_on_hold_start_date_c, mt.opp_on_hold_end_date_c)/(24.0*60*60)) END AS opp_days_on_hold_c,
COALESCE(rs1.rsf6,0) AS no_line_items_c,
COALESCE(rs1.rsf22,0) AS total_arr_c,
COALESCE(rs1.rsf5,0) AS product_arr_roll_up_c,
COALESCE(rs1.rsf19,0) AS product_arr_roll_up_temporary_c,
null AS number_of_primary_competitors_c,
(COALESCE(mt.bizible_2_bizible_opportunity_amount_c,0)!=COALESCE(CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Hero_Referrer','')) THEN 0 ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Organic','')) THEN mt.amount ELSE CASE WHEN (COALESCE(COALESCE(rs1.rsf6,0),0)>COALESCE(0,0)) THEN COALESCE(rs1.rsf7,0) ELSE CASE WHEN (COALESCE(mt.quote_arr_c,0)>COALESCE(0,0)) THEN mt.quote_arr_c ELSE CASE WHEN (COALESCE(UPPER(mt.stage_name),'')=COALESCE(UPPER('Won'),'')) THEN COALESCE(rs1.rsf7,0) ELSE CASE WHEN (COALESCE(UPPER(CONVERT(VARCHAR, jt1.geo_code_c)),'')=COALESCE(UPPER('AU'),'')) THEN (CASE WHEN ((COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_greater_100','')) OR (COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_Less_100',''))) THEN (COALESCE((COALESCE(12,0)*COALESCE(13.36,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Upsell','')) THEN (COALESCE((COALESCE(12,0)*COALESCE(3.56,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE 0 END END) ELSE CASE WHEN (COALESCE(UPPER(CONVERT(VARCHAR, jt1.geo_code_c)),'')=COALESCE(UPPER('NZ'),'')) THEN (CASE WHEN ((COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_greater_100','')) OR (COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_Less_100',''))) THEN (COALESCE((COALESCE(12,0)*COALESCE(10.64,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Upsell','')) THEN (COALESCE((COALESCE(12,0)*COALESCE(2.65,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE 0 END END) ELSE CASE WHEN (COALESCE(UPPER(CONVERT(VARCHAR, jt1.geo_code_c)),'')=COALESCE(UPPER('SG'),'')) THEN (CASE WHEN ((COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_greater_100','')) OR (COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_Less_100',''))) THEN (COALESCE((COALESCE(12,0)*COALESCE(5.00,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Upsell','')) THEN (COALESCE((COALESCE(12,0)*COALESCE(1.25,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE 0 END END) ELSE CASE WHEN (COALESCE(UPPER(CONVERT(VARCHAR, jt1.geo_code_c)),'')=COALESCE(UPPER('MY'),'')) THEN (CASE WHEN ((COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_greater_100','')) OR (COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_Less_100',''))) THEN (COALESCE((COALESCE(12,0)*COALESCE(9.99,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Upsell','')) THEN (COALESCE((COALESCE(12,0)*COALESCE(2.51,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE 0 END END) ELSE CASE WHEN (COALESCE(UPPER(CONVERT(VARCHAR, jt1.geo_code_c)),'')=COALESCE(UPPER('UK'),'')) THEN (CASE WHEN ((COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_greater_100','')) OR (COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_Less_100',''))) THEN (COALESCE((COALESCE(12,0)*COALESCE(6.65,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Upsell','')) THEN (COALESCE((COALESCE(12,0)*COALESCE(1.66,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE 0 END END) ELSE 0 END END END END END END END END END END,0)) AS sync_bizible_field_c,
(COALESCE((COALESCE(jt10.first_name,'')||COALESCE(' ','')),'')||COALESCE(jt10.last_name,'')) AS managers_name_c,
COALESCE(rs1.rsf15,0) AS list_price_2_0_keypay_org_c,
CASE WHEN ((COALESCE(COALESCE(rs1.rsf1,0),0)>COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf2,0),0)=COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf3,0),0)>COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf4,0),0)=COALESCE(0,0))) THEN 'Managed HR and Guided Payroll' ELSE CASE WHEN ((COALESCE(COALESCE(rs1.rsf1,0),0)=COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf2,0),0)>COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf3,0),0)=COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf4,0),0)>COALESCE(0,0))) THEN 'Guided HR and Managed Payroll' ELSE CASE WHEN ((COALESCE(COALESCE(rs1.rsf1,0),0)=COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf2,0),0)=COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf3,0),0)>COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf4,0),0)>COALESCE(0,0))) THEN 'Managed HR and Managed Payroll' ELSE CASE WHEN ((COALESCE(COALESCE(rs1.rsf1,0),0)=COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf2,0),0)=COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf3,0),0)>COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf4,0),0)=COALESCE(0,0))) THEN 'Managed HR' ELSE CASE WHEN ((COALESCE(COALESCE(rs1.rsf1,0),0)=COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf2,0),0)=COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf3,0),0)=COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf4,0),0)>COALESCE(0,0))) THEN 'Managed Payroll' ELSE CASE WHEN ((COALESCE(COALESCE(rs1.rsf1,0),0)>COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf2,0),0)>COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf3,0),0)=COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf4,0),0)=COALESCE(0,0))) THEN 'Guided HR and Guided Payroll' ELSE CASE WHEN ((COALESCE(COALESCE(rs1.rsf1,0),0)=COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf2,0),0)>COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf3,0),0)=COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf4,0),0)=COALESCE(0,0))) THEN 'Guided HR' ELSE CASE WHEN ((COALESCE(COALESCE(rs1.rsf1,0),0)>COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf2,0),0)=COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf3,0),0)=COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf4,0),0)=COALESCE(0,0))) THEN 'Guided Payroll' ELSE CASE WHEN ((COALESCE(mt.no_guided_payroll_zuora_c,0)>COALESCE(0,0)) AND (COALESCE(mt.no_of_guided_hr_implementations_c,0)=COALESCE(0,0)) AND (COALESCE(mt.managed_implementations_c,'')=COALESCE('HRNone',''))) THEN 'Managed HR and Guided Payroll' ELSE CASE WHEN ((COALESCE(mt.no_guided_payroll_zuora_c,0)=COALESCE(0,0)) AND (COALESCE(mt.no_of_guided_hr_implementations_c,0)>COALESCE(0,0)) AND (COALESCE(mt.managed_implementations_c,'')=COALESCE('NonePayroll',''))) THEN 'Guided HR and Managed Payroll' ELSE CASE WHEN ((COALESCE(mt.no_guided_payroll_zuora_c,0)=COALESCE(0,0)) AND (COALESCE(mt.no_of_guided_hr_implementations_c,0)=COALESCE(0,0)) AND (COALESCE(mt.managed_implementations_c,'')=COALESCE('HRPayroll',''))) THEN 'Managed HR and Managed Payroll' ELSE CASE WHEN ((COALESCE(mt.no_guided_payroll_zuora_c,0)=COALESCE(0,0)) AND (COALESCE(mt.no_of_guided_hr_implementations_c,0)=COALESCE(0,0)) AND (COALESCE(mt.managed_implementations_c,'')=COALESCE('HRNone',''))) THEN 'Managed HR' ELSE CASE WHEN ((COALESCE(mt.no_guided_payroll_zuora_c,0)=COALESCE(0,0)) AND (COALESCE(mt.no_of_guided_hr_implementations_c,0)=COALESCE(0,0)) AND (COALESCE(mt.managed_implementations_c,'')=COALESCE('NonePayroll',''))) THEN 'Managed Payroll' ELSE CASE WHEN ((COALESCE(mt.no_guided_payroll_zuora_c,0)>COALESCE(0,0)) AND (COALESCE(mt.no_of_guided_hr_implementations_c,0)>COALESCE(0,0)) AND (COALESCE(mt.managed_implementations_c,'')=COALESCE('NoneNone',''))) THEN 'Guided HR and Guided Payroll' ELSE CASE WHEN ((COALESCE(mt.no_guided_payroll_zuora_c,0)=COALESCE(0,0)) AND (COALESCE(mt.no_of_guided_hr_implementations_c,0)>COALESCE(0,0)) AND (COALESCE(mt.managed_implementations_c,'')=COALESCE('NoneNone',''))) THEN 'Guided HR' ELSE CASE WHEN ((COALESCE(mt.no_guided_payroll_zuora_c,0)>COALESCE(0,0)) AND (COALESCE(mt.no_of_guided_hr_implementations_c,0)=COALESCE(0,0)) AND (COALESCE(mt.managed_implementations_c,'')=COALESCE('NoneNone',''))) THEN 'Guided Payroll' ELSE CASE WHEN (((COALESCE(mt.no_guided_payroll_zuora_c,0)=COALESCE(0,0)) OR (mt.no_guided_payroll_zuora_c IS NULL)) AND ((COALESCE(mt.no_of_guided_hr_implementations_c,0)=COALESCE(0,0)) OR (mt.no_of_guided_hr_implementations_c IS NULL)) AND ((COALESCE(mt.managed_implementations_c,'')=COALESCE('NoneNone','')) OR (LENGTH(COALESCE(mt.managed_implementations_c,''))=0)) AND (COALESCE(COALESCE(rs1.rsf1,0),0)=COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf2,0),0)=COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf3,0),0)=COALESCE(0,0)) AND (COALESCE(COALESCE(rs1.rsf4,0),0)=COALESCE(0,0))) THEN 'No Implementation' ELSE 'See Contract' END END END END END END END END END END END END END END END END END AS implementation_type_c,
(COALESCE((COALESCE((COALESCE((COALESCE(CASE WHEN (COALESCE(UPPER(mt.type),'')=COALESCE(UPPER(''),'')) THEN 0 ELSE 20 END,0)+COALESCE(CASE WHEN (COALESCE(LENGTH(COALESCE(CONVERT(VARCHAR, EXTRACT(MONTH FROM mt.close_date)),'')),0)=COALESCE(0,0)) THEN 0 ELSE 20 END,0)),0)+COALESCE(CASE WHEN (COALESCE(mt.amount,0)<=COALESCE(0,0)) THEN 0 ELSE 20 END,0)),0)+COALESCE(CASE WHEN (COALESCE(UPPER(mt.lead_source),'')=COALESCE(UPPER(''),'')) THEN 0 ELSE 20 END,0)),0)+COALESCE(CASE WHEN (COALESCE(LENGTH(COALESCE(mt.next_step,'')),0)=COALESCE(0,0)) THEN 0 ELSE 20 END,0)) AS data_quality_score_c,
COALESCE(rs1.rsf23,0) AS one_off_product_total_amount_c,
jt2.email AS opp_contact_email_c,
CASE WHEN ((COALESCE(EXTRACT(YEAR FROM DATE(mt.created_date)),0)=COALESCE(EXTRACT(YEAR FROM mt.close_date),0)) AND (COALESCE(EXTRACT(MONTH FROM DATE(mt.created_date)),0)=COALESCE(EXTRACT(MONTH FROM mt.close_date),0)) AND mt.is_closed) THEN COALESCE(rs1.rsf5,0) ELSE 0 END AS created_closed_within_month_c,
CONVERT(VARCHAR, jt1.industry_primary_c) AS account_industry_primary_c,
COALESCE(rs1.rsf10,0) AS product_one_off_rev_roll_up_c,
COALESCE(rs1.rsf8,0) AS product_revenue_roll_up_recurring_rev_c,
CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Hero_Referrer','')) THEN 0 ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Organic','')) THEN mt.amount ELSE CASE WHEN (COALESCE(COALESCE(rs1.rsf6,0),0)>COALESCE(0,0)) THEN COALESCE(rs1.rsf7,0) ELSE CASE WHEN (COALESCE(mt.quote_arr_c,0)>COALESCE(0,0)) THEN mt.quote_arr_c ELSE CASE WHEN (COALESCE(UPPER(mt.stage_name),'')=COALESCE(UPPER('Won'),'')) THEN COALESCE(rs1.rsf7,0) ELSE CASE WHEN (COALESCE(UPPER(CONVERT(VARCHAR, jt1.geo_code_c)),'')=COALESCE(UPPER('AU'),'')) THEN (CASE WHEN ((COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_greater_100','')) OR (COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_Less_100',''))) THEN (COALESCE((COALESCE(12,0)*COALESCE(13.36,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Upsell','')) THEN (COALESCE((COALESCE(12,0)*COALESCE(3.56,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE 0 END END) ELSE CASE WHEN (COALESCE(UPPER(CONVERT(VARCHAR, jt1.geo_code_c)),'')=COALESCE(UPPER('NZ'),'')) THEN (CASE WHEN ((COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_greater_100','')) OR (COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_Less_100',''))) THEN (COALESCE((COALESCE(12,0)*COALESCE(10.64,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Upsell','')) THEN (COALESCE((COALESCE(12,0)*COALESCE(2.65,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE 0 END END) ELSE CASE WHEN (COALESCE(UPPER(CONVERT(VARCHAR, jt1.geo_code_c)),'')=COALESCE(UPPER('SG'),'')) THEN (CASE WHEN ((COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_greater_100','')) OR (COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_Less_100',''))) THEN (COALESCE((COALESCE(12,0)*COALESCE(5.00,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Upsell','')) THEN (COALESCE((COALESCE(12,0)*COALESCE(1.25,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE 0 END END) ELSE CASE WHEN (COALESCE(UPPER(CONVERT(VARCHAR, jt1.geo_code_c)),'')=COALESCE(UPPER('MY'),'')) THEN (CASE WHEN ((COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_greater_100','')) OR (COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_Less_100',''))) THEN (COALESCE((COALESCE(12,0)*COALESCE(9.99,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Upsell','')) THEN (COALESCE((COALESCE(12,0)*COALESCE(2.51,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE 0 END END) ELSE CASE WHEN (COALESCE(UPPER(CONVERT(VARCHAR, jt1.geo_code_c)),'')=COALESCE(UPPER('UK'),'')) THEN (CASE WHEN ((COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_greater_100','')) OR (COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_Less_100',''))) THEN (COALESCE((COALESCE(12,0)*COALESCE(6.65,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Upsell','')) THEN (COALESCE((COALESCE(12,0)*COALESCE(1.66,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE 0 END END) ELSE 0 END END END END END END END END END END AS annual_recurring_revenue_c,
jt1.legal_name_c AS legal_name_c,
jt1.number_of_active_contacts_c AS number_of_contacts_c,
NULLIF(COALESCE(NULLIF(COALESCE(jt2.first_name,'')||COALESCE(' ',''),''),'')||COALESCE(jt2.last_name,''),'') AS opp_contact_name_c,
COALESCE(rs1.rsf14,0) AS discount_in_services_c,
COALESCE(rs1.rsf20,0) AS product_arr_rollup_c,
CASE WHEN (COALESCE((COALESCE((COALESCE((COALESCE((COALESCE(CASE WHEN (COALESCE(UPPER(mt.type),'')=COALESCE(UPPER(''),'')) THEN 0 ELSE 20 END,0)+COALESCE(CASE WHEN (COALESCE(LENGTH(COALESCE(CONVERT(VARCHAR, EXTRACT(MONTH FROM mt.close_date)),'')),0)=COALESCE(0,0)) THEN 0 ELSE 20 END,0)),0)+COALESCE(CASE WHEN (COALESCE(mt.amount,0)<=COALESCE(0,0)) THEN 0 ELSE 20 END,0)),0)+COALESCE(CASE WHEN (COALESCE(UPPER(mt.lead_source),'')=COALESCE(UPPER(''),'')) THEN 0 ELSE 20 END,0)),0)+COALESCE(CASE WHEN (COALESCE(LENGTH(COALESCE(mt.next_step,'')),0)=COALESCE(0,0)) THEN 0 ELSE 20 END,0)),0)=COALESCE(100,0)) THEN 'All Opportunity Details Captured' ELSE (COALESCE((COALESCE((COALESCE((COALESCE((COALESCE((COALESCE((COALESCE((COALESCE((COALESCE('Missing: ','')||COALESCE(CASE WHEN (COALESCE(UPPER(mt.type),'')=COALESCE(UPPER(''),'')) THEN 'Type, ' ELSE '' END,'')),'')||COALESCE('','')),'')||COALESCE(CASE WHEN (COALESCE(LENGTH(COALESCE(CONVERT(VARCHAR, EXTRACT(MONTH FROM mt.close_date)),'')),0)=COALESCE(0,0)) THEN 'Close Date, ' ELSE '' END,'')),'')||COALESCE('','')),'')||COALESCE(CASE WHEN (COALESCE(mt.amount,0)<=COALESCE(0,0)) THEN 'Amount, ' ELSE '' END,'')),'')||COALESCE('','')),'')||COALESCE(CASE WHEN (COALESCE(UPPER(mt.lead_source),'')=COALESCE(UPPER(''),'')) THEN 'Lead Source, ' ELSE '' END,'')),'')||COALESCE('','')),'')||COALESCE(CASE WHEN (COALESCE(LENGTH(COALESCE(mt.next_step,'')),0)=COALESCE(0,0)) THEN 'Next Steps' ELSE '' END,'')) END AS data_quality_description_c,
(COALESCE(((COALESCE(COALESCE(rs1.rsf9,0),0)*COALESCE(mt.contract_term_c,0))),0)+COALESCE(COALESCE(rs1.rsf10,0),0)) AS total_contract_value_c,
null AS sf_base_url_c,
COALESCE(rs1.rsf16,0) AS total_opportunity_amount_c,
1 AS power_of_1_oppt_c,
CONVERT(VARCHAR, jt1.geo_code_c) AS geo_code_c,
CASE mt.stage_name WHEN 'Won' THEN COALESCE(rs1.rsf8,0) ELSE CASE WHEN (COALESCE(COALESCE(rs1.rsf8,0),0)>COALESCE(0,0)) THEN COALESCE(rs1.rsf8,0) ELSE CASE WHEN (COALESCE(mt.amount,0)>COALESCE(0,0)) THEN mt.amount ELSE CASE WHEN (COALESCE(UPPER(CONVERT(VARCHAR, jt1.geo_code_c)),'')=COALESCE(UPPER('AU'),'')) THEN (CASE WHEN ((COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_greater_100','')) OR (COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_Less_100',''))) THEN (COALESCE((COALESCE(12,0)*COALESCE(13.36,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Upsell','')) THEN (COALESCE((COALESCE(12,0)*COALESCE(3.56,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE 0 END END) ELSE CASE WHEN (COALESCE(UPPER(CONVERT(VARCHAR, jt1.geo_code_c)),'')=COALESCE(UPPER('NZ'),'')) THEN (CASE WHEN ((COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_greater_100','')) OR (COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_Less_100',''))) THEN (COALESCE((COALESCE(12,0)*COALESCE(10.64,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Upsell','')) THEN (COALESCE((COALESCE(12,0)*COALESCE(2.65,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE 0 END END) ELSE CASE WHEN (COALESCE(UPPER(CONVERT(VARCHAR, jt1.geo_code_c)),'')=COALESCE(UPPER('SG'),'')) THEN (CASE WHEN ((COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_greater_100','')) OR (COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_Less_100',''))) THEN (COALESCE((COALESCE(12,0)*COALESCE(5.00,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Upsell','')) THEN (COALESCE((COALESCE(12,0)*COALESCE(1.25,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE 0 END END) ELSE CASE WHEN (COALESCE(UPPER(CONVERT(VARCHAR, jt1.geo_code_c)),'')=COALESCE(UPPER('MY'),'')) THEN (CASE WHEN ((COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_greater_100','')) OR (COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_Less_100',''))) THEN (COALESCE((COALESCE(12,0)*COALESCE(9.99,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Upsell','')) THEN (COALESCE((COALESCE(12,0)*COALESCE(2.51,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE 0 END END) ELSE CASE WHEN (COALESCE(UPPER(CONVERT(VARCHAR, jt1.geo_code_c)),'')=COALESCE(UPPER('UK'),'')) THEN (CASE WHEN ((COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_greater_100','')) OR (COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_Less_100',''))) THEN (COALESCE((COALESCE(12,0)*COALESCE(6.65,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Upsell','')) THEN (COALESCE((COALESCE(12,0)*COALESCE(1.66,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE 0 END END) ELSE 0 END END END END END END END END AS sales_recognised_revenue_c,
CASE WHEN (COALESCE(COALESCE(rs1.rsf6,0),0)>COALESCE(0,0)) THEN COALESCE(rs1.rsf11,0) ELSE CASE WHEN (COALESCE(mt.quote_srr_c,0)>COALESCE(0,0)) THEN mt.quote_srr_c ELSE CASE WHEN (COALESCE(UPPER(mt.stage_name),'')=COALESCE(UPPER('Won'),'')) THEN COALESCE(rs1.rsf11,0) ELSE CASE WHEN (COALESCE(UPPER(CONVERT(VARCHAR, jt1.geo_code_c)),'')=COALESCE(UPPER('AU'),'')) THEN (CASE WHEN ((COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_greater_100','')) OR (COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_Less_100',''))) THEN (COALESCE((COALESCE(12,0)*COALESCE(13.36,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Upsell','')) THEN (COALESCE((COALESCE(12,0)*COALESCE(3.56,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE 0 END END) ELSE CASE WHEN (COALESCE(UPPER(CONVERT(VARCHAR, jt1.geo_code_c)),'')=COALESCE(UPPER('NZ'),'')) THEN (CASE WHEN ((COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_greater_100','')) OR (COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_Less_100',''))) THEN (COALESCE((COALESCE(12,0)*COALESCE(10.64,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Upsell','')) THEN (COALESCE((COALESCE(12,0)*COALESCE(2.65,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE 0 END END) ELSE CASE WHEN (COALESCE(UPPER(CONVERT(VARCHAR, jt1.geo_code_c)),'')=COALESCE(UPPER('SG'),'')) THEN (CASE WHEN ((COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_greater_100','')) OR (COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_Less_100',''))) THEN (COALESCE((COALESCE(12,0)*COALESCE(5.00,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Upsell','')) THEN (COALESCE((COALESCE(12,0)*COALESCE(1.25,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE 0 END END) ELSE CASE WHEN (COALESCE(UPPER(CONVERT(VARCHAR, jt1.geo_code_c)),'')=COALESCE(UPPER('MY'),'')) THEN (CASE WHEN ((COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_greater_100','')) OR (COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_Less_100',''))) THEN (COALESCE((COALESCE(12,0)*COALESCE(9.99,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Upsell','')) THEN (COALESCE((COALESCE(12,0)*COALESCE(2.51,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE 0 END END) ELSE CASE WHEN (COALESCE(UPPER(CONVERT(VARCHAR, jt1.geo_code_c)),'')=COALESCE(UPPER('UK'),'')) THEN (CASE WHEN ((COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_greater_100','')) OR (COALESCE(jt3.developer_name,'')=COALESCE('Direct_Sales_Employees_Less_100',''))) THEN (COALESCE((COALESCE(12,0)*COALESCE(6.65,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE CASE WHEN (COALESCE(jt3.developer_name,'')=COALESCE('Upsell','')) THEN (COALESCE((COALESCE(12,0)*COALESCE(1.66,0)),0)*COALESCE(mt.opportunity_employees_c,0)) ELSE 0 END END) ELSE 0 END END END END END END END END AS sales_recognised_revenue_2_c,
COALESCE(rs1.rsf12,0) AS list_price_2_0_eh_org_c,
jt1.company_abn_c AS company_abn_c,
mt.account_id AS salesforce_account_id_c,
CASE WHEN (COALESCE(mt.opportunity_employees_c,0)<COALESCE(151,0)) THEN 'Core' ELSE 'Mid-Market' END AS opportunity_market_c,
jt9.name AS salesforce_campaign_c,
COALESCE(rs1.rsf21,0) AS discount_in_monthly_recurring_c,
jt3.name AS record_type_text_c,
DATEADD(SECONDS, CAST((MOD((DATEDIFF(SECOND, DATE(FLOOR(1900)||'-'||FLOOR(1)||'-'||FLOOR(8)), DATE(mt.created_date))/(24.0*60*60)),7) * 24 * 60 * 60) * -1 AS INTEGER), DATE(mt.created_date)) AS start_date_of_created_week_c,
null AS mkto_si_sales_insight_c,
'<a href="' || NULLIF(COALESCE(NULLIF(COALESCE(NULLIF(COALESCE('https://www.payway.com.au/SignUp?ClientNumber=Q24002&Frequency=VARIABLE&AddressRequired=false&CustomerNumber=','')||COALESCE(mt.account_id,''),''),'')||COALESCE('&CustomerName=',''),''),'')||COALESCE(jt1.name,''),'') || '" target="' || '_blank' || '">' || 'Payway link' || '</a>' AS payway_link_c,
COALESCE(rs1.rsf3,0) AS no_managed_hr_implementation_products_c,
CASE WHEN mt.opportunity_is_closed_c THEN (DATEDIFF(SECOND, DATE(mt.created_date), mt.opportunity_closed_date_c)/(24.0*60*60)) ELSE (DATEDIFF(SECOND, DATE(mt.created_date), CURRENT_DATE)/(24.0*60*60)) END AS opportunity_age_c,
CASE WHEN ((COALESCE(EXTRACT(YEAR FROM DATE(mt.created_date)),0)=COALESCE(EXTRACT(YEAR FROM mt.close_date),0)) AND (COALESCE(EXTRACT(MONTH FROM DATE(mt.created_date)),0)=COALESCE(EXTRACT(MONTH FROM mt.close_date),0)) AND mt.is_closed AND (NOT (COALESCE(UPPER(mt.existing_customer_revenue_type_c),'')=COALESCE(UPPER('ANZ > Paid'),'')))) THEN (CASE WHEN (COALESCE(COALESCE(rs1.rsf8,0),0)=COALESCE(0,0)) THEN mt.amount ELSE COALESCE(rs1.rsf8,0) END) ELSE 0 END AS created_closed_recurring_rev_c,
null AS hero_hub_opportunity_c
 FROM dev.salesforce.opportunity AS mt LEFT JOIN dev.salesforce.account AS jt1 ON mt.account_id=jt1.id LEFT JOIN dev.salesforce.user AS jt4 ON mt.owner_id=jt4.id LEFT JOIN dev.salesforce.user AS jt7 ON mt.created_by_id=jt7.id LEFT JOIN dev.salesforce.campaign AS jt9 ON mt.campaign_id=jt9.id LEFT JOIN dev.salesforce.record_type AS jt3 ON mt.record_type_id=jt3.id LEFT JOIN dev.salesforce.pricebook_2 AS jt11 ON mt.pricebook_2_id=jt11.id LEFT JOIN dev.salesforce.contact AS jt2 ON mt.contact_c=jt2.id LEFT JOIN dev.salesforce.eh_org_c AS jt6 ON jt1.eh_org_c=jt6.id LEFT JOIN dev.salesforce.profile AS jt5 ON jt4.profile_id=jt5.id LEFT JOIN dev.salesforce.user AS jt10 ON jt4.manager_id=jt10.id LEFT JOIN dev.salesforce.profile AS jt8 ON jt7.profile_id=jt8.id LEFT JOIN (SELECT ch1.opportunity_id AS par1,SUM(CASE WHEN (COALESCE(UPPER(ch1.revenue_type_c) IN (UPPER('Monthly Recurring - Usage')),FALSE)) THEN CASE WHEN (COALESCE(CASE WHEN ch1.quantity<0 THEN FLOOR(ch1.quantity)+1 ELSE FLOOR(ch1.quantity) END,0)=COALESCE(ch1.quantity,0)) THEN (COALESCE(ch1.sales_price_unique_c,0)*COALESCE(ch1.quantity,0)) ELSE ROUND((COALESCE(ch1.sales_price_unique_c,0)*COALESCE(ch1.quantity,0)),0) END ELSE NULL END) AS rsf9,COUNT(ch1.Id) AS rsf6,SUM(CASE WHEN (COALESCE(UPPER(ch1.revenue_type_c) IN (UPPER('Monthly Recurring - Usage')),FALSE)) THEN CASE WHEN ((ch1.list_price_2_0_c IS NULL) OR (COALESCE(ch1.list_price_2_0_c,0)=COALESCE(0,0))) THEN CASE WHEN (COALESCE(UPPER(ch1.revenue_type_c),'')=COALESCE(UPPER('One-Off'),'')) THEN (COALESCE(((COALESCE((COALESCE(ch1.list_price,0)-COALESCE(ch1.discount_dollars_c,0)),0)-COALESCE(ch1.cogs_c,0))),0)*COALESCE(ch1.quantity,0)) ELSE (COALESCE((COALESCE(((COALESCE((COALESCE(ch1.list_price,0)-COALESCE(ch1.discount_dollars_c,0)),0)-COALESCE(ch1.cogs_c,0))),0)*COALESCE(12,0)),0)*COALESCE(ch1.quantity,0)) END ELSE CASE WHEN (COALESCE(UPPER(ch1.revenue_type_c),'')=COALESCE(UPPER('One-Off'),'')) THEN (COALESCE(ch1.list_price_2_0_c,0)*COALESCE(ch1.quantity,0)) ELSE (COALESCE((COALESCE(ch1.list_price_2_0_c,0)*COALESCE(ch1.quantity,0)),0)*COALESCE(12,0)) END END ELSE NULL END) AS rsf5,SUM(CASE WHEN (COALESCE(UPPER(ch1.revenue_type_c) IN (UPPER('Monthly Recurring - Usage')),FALSE)) THEN CASE WHEN ((ch1.list_price_2_0_c IS NULL) OR (COALESCE(ch1.list_price_2_0_c,0)=COALESCE(0,0))) THEN CASE WHEN (COALESCE(UPPER(ch1.revenue_type_c),'')=COALESCE(UPPER('One-Off'),'')) THEN (COALESCE(((COALESCE((COALESCE(ch1.list_price,0)-COALESCE(ch1.discount_dollars_c,0)),0)-COALESCE(ch1.cogs_c,0))),0)*COALESCE(ch1.quantity,0)) ELSE (COALESCE((COALESCE(((COALESCE((COALESCE(ch1.list_price,0)-COALESCE(ch1.discount_dollars_c,0)),0)-COALESCE(ch1.cogs_c,0))),0)*COALESCE(12,0)),0)*COALESCE(ch1.quantity,0)) END ELSE CASE WHEN (COALESCE(UPPER(ch1.revenue_type_c),'')=COALESCE(UPPER('One-Off'),'')) THEN (COALESCE(ch1.list_price_2_0_c,0)*COALESCE(ch1.quantity,0)) ELSE (COALESCE((COALESCE(ch1.list_price_2_0_c,0)*COALESCE(ch1.quantity,0)),0)*COALESCE(12,0)) END END ELSE NULL END) AS rsf8,SUM(CASE WHEN (COALESCE(UPPER(ch1.revenue_type_c),'')=COALESCE(UPPER('Monthly Recurring - Usage'),'')) THEN (COALESCE((COALESCE(((COALESCE(ch1.list_price,0)-COALESCE(ch1.discount_dollars_c,0))),0)*COALESCE(ch1.quantity,0)),0)*COALESCE(12,0)) ELSE 0 END) AS rsf7,SUM(CASE WHEN (COALESCE(ch1.product_code_text_c IN ('A005','A006'),FALSE)) THEN 1 ELSE 0 END) AS rsf18,SUM(CASE WHEN (COALESCE(UPPER(ch1.revenue_type_c) IN (UPPER('Monthly Recurring - Usage')),FALSE)) THEN CASE WHEN ((ch1.list_price_2_0_c IS NULL) OR (COALESCE(ch1.list_price_2_0_c,0)=COALESCE(0,0))) THEN CASE WHEN (COALESCE(UPPER(ch1.revenue_type_c),'')=COALESCE(UPPER('One-Off'),'')) THEN (COALESCE(((COALESCE((COALESCE(ch1.list_price,0)-COALESCE(ch1.discount_dollars_c,0)),0)-COALESCE(ch1.cogs_c,0))),0)*COALESCE(ch1.quantity,0)) ELSE (COALESCE((COALESCE(((COALESCE((COALESCE(ch1.list_price,0)-COALESCE(ch1.discount_dollars_c,0)),0)-COALESCE(ch1.cogs_c,0))),0)*COALESCE(12,0)),0)*COALESCE(ch1.quantity,0)) END ELSE CASE WHEN (COALESCE(UPPER(ch1.revenue_type_c),'')=COALESCE(UPPER('One-Off'),'')) THEN (COALESCE(ch1.list_price_2_0_c,0)*COALESCE(ch1.quantity,0)) ELSE (COALESCE((COALESCE(ch1.list_price_2_0_c,0)*COALESCE(ch1.quantity,0)),0)*COALESCE(12,0)) END END ELSE NULL END) AS rsf19,SUM(CASE WHEN (COALESCE(UPPER(ch1.revenue_type_c) IN (UPPER('One-Off')),FALSE)) THEN ch1.discount_dollars_c ELSE NULL END) AS rsf14,SUM(CASE WHEN (ch1.product_code_text_c LIKE '%HP%') THEN ch1.list_price_2_0_c ELSE NULL END) AS rsf15,SUM(ch1.total_price_backup_c) AS rsf16,COUNT(ch1.Id) AS rsf17,SUM(CASE WHEN (COALESCE(UPPER(ch1.revenue_type_c) IN (UPPER('One-Off')),FALSE)) THEN CASE WHEN ((ch1.list_price_2_0_c IS NULL) OR (COALESCE(ch1.list_price_2_0_c,0)=COALESCE(0,0))) THEN CASE WHEN (COALESCE(UPPER(ch1.revenue_type_c),'')=COALESCE(UPPER('One-Off'),'')) THEN (COALESCE(((COALESCE((COALESCE(ch1.list_price,0)-COALESCE(ch1.discount_dollars_c,0)),0)-COALESCE(ch1.cogs_c,0))),0)*COALESCE(ch1.quantity,0)) ELSE (COALESCE((COALESCE(((COALESCE((COALESCE(ch1.list_price,0)-COALESCE(ch1.discount_dollars_c,0)),0)-COALESCE(ch1.cogs_c,0))),0)*COALESCE(12,0)),0)*COALESCE(ch1.quantity,0)) END ELSE CASE WHEN (COALESCE(UPPER(ch1.revenue_type_c),'')=COALESCE(UPPER('One-Off'),'')) THEN (COALESCE(ch1.list_price_2_0_c,0)*COALESCE(ch1.quantity,0)) ELSE (COALESCE((COALESCE(ch1.list_price_2_0_c,0)*COALESCE(ch1.quantity,0)),0)*COALESCE(12,0)) END END ELSE NULL END) AS rsf10,SUM(CASE WHEN (COALESCE(UPPER(ch1.revenue_type_c) IN (UPPER('Monthly Recurring - Usage')),FALSE)) THEN ch1.discount_dollars_c ELSE NULL END) AS rsf21,SUM(CASE WHEN (COALESCE(ch1.product_code_text_c IN ('S013','S015'),FALSE)) THEN 1 ELSE 0 END) AS rsf2,SUM(ch1.opportunity_product_srr_c) AS rsf11,SUM(CASE WHEN (COALESCE(ch1.product_code_text_c IN ('S014','S016','HP003SG','HP003NZ','HP003UK'),FALSE)) THEN 1 ELSE 0 END) AS rsf1,SUM(ch1.arr_annuity_c) AS rsf22,SUM(ch1.list_price_2_0_c) AS rsf12,SUM(CASE WHEN (COALESCE(UPPER(ch1.revenue_type_c) IN (UPPER('One-Off')),FALSE)) THEN ch1.total_price_backup_c ELSE NULL END) AS rsf23,SUM(CASE WHEN (COALESCE(ch1.product_code_text_c IN ('S003'),FALSE)) THEN 1 ELSE 0 END) AS rsf4,SUM(CASE WHEN (COALESCE(CASE WHEN (COALESCE(CASE WHEN ((ch1.list_price_2_0_c IS NULL) OR (COALESCE(ch1.list_price_2_0_c,0)=COALESCE(0,0))) THEN CASE WHEN (COALESCE(UPPER(ch1.revenue_type_c),'')=COALESCE(UPPER('One-Off'),'')) THEN (COALESCE(((COALESCE((COALESCE(ch1.list_price,0)-COALESCE(ch1.discount_dollars_c,0)),0)-COALESCE(ch1.cogs_c,0))),0)*COALESCE(ch1.quantity,0)) ELSE (COALESCE((COALESCE(((COALESCE((COALESCE(ch1.list_price,0)-COALESCE(ch1.discount_dollars_c,0)),0)-COALESCE(ch1.cogs_c,0))),0)*COALESCE(12,0)),0)*COALESCE(ch1.quantity,0)) END ELSE CASE WHEN (COALESCE(UPPER(ch1.revenue_type_c),'')=COALESCE(UPPER('One-Off'),'')) THEN (COALESCE(ch1.list_price_2_0_c,0)*COALESCE(ch1.quantity,0)) ELSE (COALESCE((COALESCE(ch1.list_price_2_0_c,0)*COALESCE(ch1.quantity,0)),0)*COALESCE(12,0)) END END,0)=COALESCE(ch1.total_price,0)) THEN TRUE ELSE FALSE END IN (False),FALSE)) AND (COALESCE(UPPER(ch1.revenue_type_c) IN (UPPER('Monthly Recurring - Usage')),FALSE)) THEN 1 ELSE 0 END) AS rsf24,SUM(CASE WHEN (COALESCE(ch1.product_code_text_c IN ('S001'),FALSE)) THEN 1 ELSE 0 END) AS rsf3,SUM(CASE WHEN ((ch1.list_price_2_0_c IS NULL) OR (COALESCE(ch1.list_price_2_0_c,0)=COALESCE(0,0))) THEN CASE WHEN (COALESCE(UPPER(ch1.revenue_type_c),'')=COALESCE(UPPER('One-Off'),'')) THEN (COALESCE(((COALESCE((COALESCE(ch1.list_price,0)-COALESCE(ch1.discount_dollars_c,0)),0)-COALESCE(ch1.cogs_c,0))),0)*COALESCE(ch1.quantity,0)) ELSE (COALESCE((COALESCE(((COALESCE((COALESCE(ch1.list_price,0)-COALESCE(ch1.discount_dollars_c,0)),0)-COALESCE(ch1.cogs_c,0))),0)*COALESCE(12,0)),0)*COALESCE(ch1.quantity,0)) END ELSE CASE WHEN (COALESCE(UPPER(ch1.revenue_type_c),'')=COALESCE(UPPER('One-Off'),'')) THEN (COALESCE(ch1.list_price_2_0_c,0)*COALESCE(ch1.quantity,0)) ELSE (COALESCE((COALESCE(ch1.list_price_2_0_c,0)*COALESCE(ch1.quantity,0)),0)*COALESCE(12,0)) END END) AS rsf13,SUM(CASE WHEN ((ch1.list_price_2_0_c IS NULL) OR (COALESCE(ch1.list_price_2_0_c,0)=COALESCE(0,0))) THEN CASE WHEN (COALESCE(UPPER(ch1.revenue_type_c),'')=COALESCE(UPPER('One-Off'),'')) THEN (COALESCE(((COALESCE((COALESCE(ch1.list_price,0)-COALESCE(ch1.discount_dollars_c,0)),0)-COALESCE(ch1.cogs_c,0))),0)*COALESCE(ch1.quantity,0)) ELSE (COALESCE((COALESCE(((COALESCE((COALESCE(ch1.list_price,0)-COALESCE(ch1.discount_dollars_c,0)),0)-COALESCE(ch1.cogs_c,0))),0)*COALESCE(12,0)),0)*COALESCE(ch1.quantity,0)) END ELSE CASE WHEN (COALESCE(UPPER(ch1.revenue_type_c),'')=COALESCE(UPPER('One-Off'),'')) THEN (COALESCE(ch1.list_price_2_0_c,0)*COALESCE(ch1.quantity,0)) ELSE (COALESCE((COALESCE(ch1.list_price_2_0_c,0)*COALESCE(ch1.quantity,0)),0)*COALESCE(12,0)) END END) AS rsf20 FROM dev.salesforce.opportunity_line_item AS ch1 
WHERE NOT ch1._fivetran_deleted GROUP BY par1) AS rs1 ON rs1.par1=mt.id 
WHERE NOT mt._fivetran_deleted

