version: 2

models:
  - name: exports_braze_users
    schema: exports
    description: "Export user data to Braze, refer to https://docs.google.com/spreadsheets/d/1CBgrzO36ZiZSj8a7xqvtTnxLlz46NzxxXKpe6Zvue40/edit#gid=2035763922"
    tests:
      - dbt_utils.relationships_where:
          column_name: user_id
          to: source('postgres_public', 'user_employment_histories')
          field: user_id
          from_condition: candidate_recent_job_title is not NULL 
          to_condition: job_title is not NULL or industry_standard_job_title is not NULL  
    columns:
      - name: user_uuid
        tests:
          - not_null
          - unique
      - name: email
        tests:
          - not_null
      - name: phone_number_e164 
        tests:
          # Testing AU phone number.
          - dbt_utils.expression_is_true:
              expression: "not like '+610%'"

      - name: country
        tests:
          - dbt_utils.expression_is_true:
              expression: 'is not null'
              config:
                where: "alpha_two_letter is not null"
      - name: user_actively_employed 
        tests:
          - dbt_utils.not_constant
      - name: user_is_candidate 
        tests:
          - dbt_utils.not_constant
          - dbt_utils.expression_is_true:
              expression: "is true"
              config:
                where: "user_signin_source = 'career_page'"
      # if user're employed, they should have full informaton 
      - name: first_name
        tests:
          - dbt_utils.expression_is_true:
              expression: 'is not null'
              config:
                where: "user_actively_employed is true"
      - name: last_name
        tests:
          - dbt_utils.expression_is_true:
              expression: 'is not null'
              config:
                where: "user_actively_employed is true"
      - name: email
        tests:
          - dbt_utils.expression_is_true:
              expression: 'is not null'
              config:
                where: "user_actively_employed is true"

      - name: postcode
        tests:
          - dbt_expectations.expect_column_to_exist

      - name: gender
        description: "(string) “M”, “F”, “O” (other), “N” (not applicable), “P” (prefer not to say) or nil (unknown)."
        tests:
          - dbt_expectations.expect_column_to_exist
          - accepted_values:
              values: ['P', 'O', 'F', 'M']

      - name: home_city
        tests:
          - dbt_expectations.expect_column_to_exist

      - name: is_marketing_consented  
        tests:
          - dbt_utils.expression_is_true:
              expression: " = false"
              config:
                where: "marketing_consented_at is null"

      - name: benefits_enabled
        tests:
          - not_null

      - name: candidate_recent_job_title
        description: "Most recent (standard) job title of candidate on jobs.swag.com" 
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_utils.not_constant

      - name: user_id
        description: "Numeric user's id"
        tests:
          - not_null

  - name: exports_v_braze_email_unsubscriptions
    schema: exports
    tests:
      - dbt_utils.fewer_rows_than:
          compare_model: ref('exports_braze_users')
    columns:
      - name: external_id
        tests:
          - not_null
      - name: email
        tests:
          - not_null
          - unique

  - name: int_exports__sign_in_app_events
    schema: exports

  - name: int_exports__swag_candidate_events
    schema: exports

  - name: exports_braze_user_events
    schema: exports
    description: "Full details at https://docs.google.com/spreadsheets/d/1CBgrzO36ZiZSj8a7xqvtTnxLlz46NzxxXKpe6Zvue40/edit#gid=2035763922"
    tests:
      - dbt_utils.expression_is_true:
          expression: "event_prop_public_profile_enabled is null"
          config:
            where: "event_name != 'candidate_profile_completed' and event_name != 'candidate_cv_uploaded' and event_name != 'candidate_public_profile'"
      - dbt_utils.recency:
          datepart: day
          field: event_time
          interval: 1
    columns:
      - name: user_uuid 
        tests:
          - not_null
      - name: event_id
        tests:
          - not_null
          - unique
      - name: event_time
        tests:
          - not_null
      - name: event_name
        tests:
          - not_null

  - name: exports_braze_payloads
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - external_id
            - updated_at
    schema: exports
    columns:
      - name: external_id
        tests:
          - dbt_expectations.expect_column_to_exist
          - not_null

      - name: payload
        tests:
          - dbt_expectations.expect_column_to_exist
          - not_null

      - name: updated_at
        tests:
          - dbt_expectations.expect_column_to_exist
          - not_null
