name: Data Governance

on:
  push:
    branches:
    - main
    paths:
    - 'governance/**'

jobs:
  redshift-permission-grant:
    runs-on: [self-hosted, ci-general]
    steps:
    - name: ⚡ Check out repository code
      uses: actions/checkout@v3

    - id: 'changes'
      uses: dorny/paths-filter@v2
      with:
        filters: |
          permissions:
            - 'governance/redshift_permission/permissions.yml'

    - name: 'Install redfrost'
      if: steps.changes.outputs.permissions == 'true'
      run: |
        curl -L -H "Accept: application/octet-stream" \
          -H "Authorization: Bearer ${{ secrets.REDFROST_GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" -o redfrost-linux-amd64 \
          https://api.github.com/repos/Thinkei/redfrost/releases/assets/133361606
        chmod +x redfrost-linux-amd64

    - name: 'Check permission'
      if: steps.changes.outputs.permissions == 'true'
      shell: bash
      run: |
        ./redfrost-linux-amd64 run --check --config ./governance/redshift_permission/permissions.yml --host "${{ secrets.REDSHIFT_HOST }}" --username "${{ secrets.RS_GH_USERNAME }}" --database "dev" --password "${{ secrets.RS_GH_PASSWORD }}"

    - name: 'Grant permission'
      if: steps.changes.outputs.permissions == 'true'
      shell: bash
      run: |
        ./redfrost-linux-amd64 run --live --config ./governance/redshift_permission/permissions.yml --host "${{ secrets.REDSHIFT_HOST }}" --username "${{ secrets.RS_GH_USERNAME }}" --database "dev" --password "${{ secrets.RS_GH_PASSWORD }}"
